# Generated by Django 4.2 on 2024-12-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_nature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crump_title_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('crump_subtitle_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('crump_photo_contact', models.ImageField(blank=True, upload_to='photos/contact/%Y/%m/')),
                ('form_title_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('form_subtitle_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('address_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('worktime_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('cont_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
