# Generated by Django 4.2 on 2024-12-27 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_contact_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_block', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitle_block', models.TextField(blank=True, null=True)),
                ('title_video', models.CharField(blank=True, max_length=255, null=True)),
                ('text_video', models.TextField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('link_frame_video', models.TextField(blank=True, null=True)),
                ('link_service', models.CharField(blank=True, max_length=255, null=True)),
                ('width_video', models.CharField(blank=True, max_length=255, null=True)),
                ('height_video', models.CharField(blank=True, max_length=255, null=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='brieftdraft',
            options={'verbose_name': 'ICO', 'verbose_name_plural': 'ICO'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['time_create', 'crump_title_contact'], 'verbose_name': 'Контакты 1', 'verbose_name_plural': 'Контакты 1'},
        ),
        migrations.AlterModelOptions(
            name='contact_1',
            options={'verbose_name': 'О нас', 'verbose_name_plural': 'О нас'},
        ),
        migrations.AlterModelOptions(
            name='nature',
            options={'verbose_name': 'Экология', 'verbose_name_plural': 'Экология'},
        ),
        migrations.RenameField(
            model_name='contact_1',
            old_name='crump_title_contact',
            new_name='title_banner',
        ),
        migrations.RemoveField(
            model_name='contact_1',
            name='crump_photo_contact',
        ),
        migrations.AddField(
            model_name='contact_1',
            name='photo_banner',
            field=models.ImageField(blank=True, null=True, upload_to='photos/contact/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='nature',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Текс статьи'),
        ),
        migrations.AlterField(
            model_name='nature',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Публикация'),
        ),
        migrations.AlterField(
            model_name='nature',
            name='photo',
            field=models.ImageField(upload_to='photos/nature/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='nature',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='nature',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='nature',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
    ]
