# Generated by Django 4.2 on 2024-12-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_video_alter_brieftdraft_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_banner', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitle_banner', models.CharField(blank=True, max_length=255, null=True)),
                ('photo_banner', models.ImageField(blank=True, null=True, upload_to='photos/about/%Y/%m/')),
                ('title_block_left', models.CharField(blank=True, max_length=255, null=True)),
                ('title_block_right', models.CharField(blank=True, max_length=255, null=True)),
                ('title_call', models.CharField(blank=True, max_length=255, null=True)),
                ('text_call', models.TextField(blank=True, null=True)),
                ('title_price', models.CharField(blank=True, max_length=255, null=True)),
                ('text_price', models.TextField(blank=True, null=True)),
                ('title_order', models.CharField(blank=True, max_length=255, null=True)),
                ('text_order', models.TextField(blank=True, null=True)),
                ('title_qly', models.CharField(blank=True, max_length=255, null=True)),
                ('text_qly', models.TextField(blank=True, null=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['time_create', 'title_block'], 'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
        migrations.AlterField(
            model_name='video',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='video',
            name='height_video',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Высота видео'),
        ),
        migrations.AlterField(
            model_name='video',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Публикация'),
        ),
        migrations.AlterField(
            model_name='video',
            name='link_frame_video',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка на фрейм'),
        ),
        migrations.AlterField(
            model_name='video',
            name='link_service',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на сервис'),
        ),
        migrations.AlterField(
            model_name='video',
            name='subtitle_block',
            field=models.TextField(blank=True, null=True, verbose_name='Подзаголовок блока'),
        ),
        migrations.AlterField(
            model_name='video',
            name='text_video',
            field=models.TextField(blank=True, null=True, verbose_name='Описание видео'),
        ),
        migrations.AlterField(
            model_name='video',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='video',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title_block',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок блока'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title_video',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название видео'),
        ),
        migrations.AlterField(
            model_name='video',
            name='width_video',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ширина видео'),
        ),
    ]
