# Generated by Django 4.2 on 2024-12-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_about_alter_video_options_alter_video_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('profession', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/')),
                ('author', models.CharField(blank=True, max_length=255)),
                ('telegram', models.CharField(blank=True, max_length=255, null=True)),
                ('vk', models.CharField(blank=True, max_length=255, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=255, null=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команда',
            },
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'ordering': ['time_create', 'title_banner'], 'verbose_name': 'О нас', 'verbose_name_plural': 'О нас'},
        ),
        migrations.AlterField(
            model_name='about',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Публикация'),
        ),
        migrations.AlterField(
            model_name='about',
            name='photo_banner',
            field=models.ImageField(blank=True, null=True, upload_to='photos/about/%Y/%m/', verbose_name='Изображение баннера'),
        ),
        migrations.AlterField(
            model_name='about',
            name='subtitle_banner',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='about',
            name='text_call',
            field=models.TextField(blank=True, null=True, verbose_name='Текст связи'),
        ),
        migrations.AlterField(
            model_name='about',
            name='text_order',
            field=models.TextField(blank=True, null=True, verbose_name='Текст заказа'),
        ),
        migrations.AlterField(
            model_name='about',
            name='text_price',
            field=models.TextField(blank=True, null=True, verbose_name='Текст текст цены'),
        ),
        migrations.AlterField(
            model_name='about',
            name='text_qly',
            field=models.TextField(blank=True, null=True, verbose_name='Текст кач-ва'),
        ),
        migrations.AlterField(
            model_name='about',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='about',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='about',
            name='title_banner',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='about',
            name='title_block_left',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок левого блока'),
        ),
        migrations.AlterField(
            model_name='about',
            name='title_block_right',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок правого  блока'),
        ),
        migrations.AlterField(
            model_name='about',
            name='title_call',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок связь'),
        ),
        migrations.AlterField(
            model_name='about',
            name='title_order',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок заказа'),
        ),
        migrations.AlterField(
            model_name='about',
            name='title_price',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок цены'),
        ),
        migrations.AlterField(
            model_name='about',
            name='title_qly',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок кач-ва'),
        ),
    ]
