# Generated by Django 4.2 on 2025-01-12 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_team_alter_about_options_alter_about_is_published_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diamond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок страницы')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок страницы')),
                ('title_block', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('subtitle_block', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок')),
                ('content_block', models.TextField(blank=True, null=True, verbose_name='Текст блока')),
                ('image_block', models.ImageField(blank=True, upload_to='photos/diamonds/%Y/%m/', verbose_name='Фото')),
                ('position_block', models.CharField(blank=True, max_length=255, null=True, verbose_name='Позиция блока')),
                ('dopol_block', models.TextField(blank=True, null=True, verbose_name='Дополнительно')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
            ],
            options={
                'verbose_name': 'Бриллианты',
                'verbose_name_plural': 'Бриллианты',
            },
        ),
        migrations.AlterField(
            model_name='team',
            name='author',
            field=models.CharField(blank=True, max_length=255, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='team',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Публикация'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='team',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='team',
            name='profession',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Профессия'),
        ),
        migrations.AlterField(
            model_name='team',
            name='telegram',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='telegram'),
        ),
        migrations.AlterField(
            model_name='team',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='team',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='team',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='team',
            name='vk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='vk'),
        ),
        migrations.AlterField(
            model_name='team',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='whatsapp'),
        ),
    ]
