# Generated by Django 4.2 on 2025-01-13 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_diamond_alter_team_author_alter_team_is_published_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diamond',
            old_name='content_block',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='diamond',
            old_name='dopol_block',
            new_name='dop',
        ),
        migrations.RenameField(
            model_name='diamond',
            old_name='image_block',
            new_name='photo',
        ),
        migrations.RemoveField(
            model_name='diamond',
            name='position_block',
        ),
        migrations.RemoveField(
            model_name='diamond',
            name='subtitle_block',
        ),
        migrations.RemoveField(
            model_name='diamond',
            name='title_block',
        ),
        migrations.AddField(
            model_name='diamond',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Позиция блока справа'),
        ),
        migrations.AlterField(
            model_name='diamond',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='diamond',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
    ]
