# Generated by Django 4.2 on 2025-01-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_weddingrings_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Earring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Текст блока')),
                ('photo', models.ImageField(blank=True, upload_to='photos/earrings/%Y/%m/', verbose_name='Фото')),
                ('position', models.BooleanField(default=False, verbose_name='Позиция блока справа')),
                ('dop', models.TextField(blank=True, null=True, verbose_name='Дополнительно')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
            ],
            options={
                'verbose_name': 'Серьги, подвески, кулоны',
                'verbose_name_plural': 'Серьги, подвески, кулоны',
            },
        ),
    ]
