# Generated by Django 4.2 on 2025-02-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_callbackrequest_delete_contactback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callbackrequest',
            options={'verbose_name': 'Сообщения пользователей', 'verbose_name_plural': 'Сообщения пользователей'},
        ),
        migrations.RemoveField(
            model_name='callbackrequest',
            name='phone',
        ),
        migrations.AddField(
            model_name='callbackrequest',
            name='email',
            field=models.EmailField(default=1, max_length=100, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
