# Generated by Django 4.2 on 2025-02-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_callbackrequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='callbackrequest',
            name='message',
            field=models.CharField(default=1, max_length=500, verbose_name='Сообщение'),
            preserve_default=False,
        ),
    ]
