# Generated by Django 4.2 on 2025-02-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_callbackrequest_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='callbackrequest',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
    ]
