# Generated by Django 4.2 on 2025-02-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_callback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_banner', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок баннера')),
                ('subtitle_banner', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок баннера')),
                ('photo_banner', models.ImageField(blank=True, upload_to='photos/badges/%Y/%m/', verbose_name='Фото баннера')),
                ('list1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание 1')),
                ('list2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание 4')),
                ('dop', models.TextField(blank=True, null=True, verbose_name='Дополнительно')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
            ],
            options={
                'verbose_name': 'Нагрудныe знаки',
                'verbose_name_plural': 'Нагрудныe знаки',
            },
        ),
        migrations.CreateModel(
            name='BadgeFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='photos/badges/%Y/%m/', verbose_name='Фото баннера')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
            ],
            options={
                'verbose_name': 'Фото для нагрудных знаков',
                'verbose_name_plural': 'Фото для нагрудных знаков',
            },
        ),
        migrations.DeleteModel(
            name='Callback',
        ),
    ]
