# Generated by Django 4.2 on 2025-02-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_badge_badgefoto_delete_callback'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='list3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание 3'),
        ),
        migrations.AddField(
            model_name='badge',
            name='list4',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание 4'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='list2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание 2'),
        ),
    ]
