# Generated by Django 4.2 on 2025-02-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_badge_list3_badge_list4_alter_badge_list2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='photo_banner',
            field=models.ImageField(blank=True, upload_to='photos/badges_foto/%Y/%m/', verbose_name='Фото баннера'),
        ),
    ]
