# Generated by Django 4.2 on 2025-02-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_badge_photo_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='photo_banner',
            field=models.ImageField(blank=True, upload_to='photos/badges/%Y/%m/', verbose_name='Фото баннера'),
        ),
    ]
