# Generated by Django 4.2 on 2025-02-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_badge_photo_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgefoto',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
    ]
