# Generated by Django 4.2 on 2025-02-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_badgefoto_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgefoto',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/badgesfoto/%Y/%m/', verbose_name='Фото баннера'),
        ),
    ]
