# Generated by Django 4.2 on 2025-02-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_badgefoto_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='title_list',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок описаний'),
        ),
    ]
