# Generated by Django 4.2 on 2025-02-14 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_remove_price_name_remove_price_num_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_banner', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок баннера')),
                ('subtitle_banner', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок баннера')),
                ('photo_banner', models.ImageField(blank=True, upload_to='photos/badges/%Y/%m/', verbose_name='Фото баннера')),
                ('title_list1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок описаний')),
                ('title_list2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок прейскуранта')),
                ('list1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Прейскурант 1')),
                ('list2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Прейскурант 2')),
                ('list3', models.CharField(blank=True, max_length=255, null=True, verbose_name='Прейскурант 3')),
                ('list4', models.CharField(blank=True, max_length=255, null=True, verbose_name='Прейскурант 4')),
                ('list5', models.CharField(blank=True, max_length=255, null=True, verbose_name='Прейскурант 5')),
                ('dop', models.TextField(blank=True, null=True, verbose_name='Дополнительно')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
            ],
            options={
                'verbose_name': 'Литье',
                'verbose_name_plural': 'Литье',
            },
        ),
    ]
