# Generated by Django 4.2 on 2025-02-14 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_cast'),
    ]

    operations = [
        migrations.CreateModel(
            name='CastFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('photo', models.ImageField(blank=True, upload_to='photos/cast/%Y/%m/', verbose_name='Фото баннера')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
            ],
            options={
                'verbose_name': 'Фото литья',
                'verbose_name_plural': 'Фото литья',
            },
        ),
        migrations.AlterField(
            model_name='cast',
            name='photo_banner',
            field=models.ImageField(blank=True, upload_to='photos/cast/%Y/%m/', verbose_name='Фото баннера'),
        ),
    ]
