# Generated by Django 5.1 on 2025-02-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_sketch_sketchfoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sketch',
            name='photo_banner',
            field=models.ImageField(blank=True, upload_to='photos/sketches/%Y/%m/', verbose_name='Фото баннера'),
        ),
    ]
