# Generated by Django 5.1 on 2025-02-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_modeled_modeledfoto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modeled',
            options={'verbose_name': '3D модели', 'verbose_name_plural': '3D модели'},
        ),
        migrations.AlterModelOptions(
            name='modeledfoto',
            options={'verbose_name': 'Фото 3D модели', 'verbose_name_plural': 'Фото 3D модели'},
        ),
        migrations.AlterField(
            model_name='modeledfoto',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/models/%Y/%m/', verbose_name='Фото баннера'),
        ),
    ]
