# Generated by Django 5.1 on 2025-02-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_alter_modeled_options_alter_modeledfoto_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeled',
            name='photo_banner',
            field=models.ImageField(blank=True, upload_to='photos/models/%Y/%m/', verbose_name='Фото баннера'),
        ),
    ]
