# Generated by Django 5.1 on 2025-02-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_alter_modeled_photo_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeledVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_video', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название видео')),
                ('text_video', models.TextField(blank=True, null=True, verbose_name='Описание видео')),
                ('author', models.CharField(blank=True, max_length=255, null=True, verbose_name='Автор')),
                ('link_frame_video', models.TextField(blank=True, null=True, verbose_name='Ссылка на фрейм')),
                ('link_service', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на сервис')),
                ('width_video', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ширина видео')),
                ('height_video', models.CharField(blank=True, max_length=255, null=True, verbose_name='Высота видео')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
            ],
            options={
                'verbose_name': 'Видео 3D Модели',
                'verbose_name_plural': 'Видео',
                'ordering': ['time_create', 'title_video'],
            },
        ),
    ]
