# Generated by Django 5.1 on 2025-02-19 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_modeledvideo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modeledvideo',
            options={'ordering': ['time_create', 'title_video'], 'verbose_name': 'Видео 3D Модели', 'verbose_name_plural': 'Видео 3D Модели'},
        ),
    ]
