# Generated by Django 5.1 on 2025-02-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_alter_modeledvideo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeledvideo',
            name='subtitle_block',
            field=models.TextField(blank=True, null=True, verbose_name='Подзаголовок блока'),
        ),
        migrations.AddField(
            model_name='modeledvideo',
            name='title_block',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок блока'),
        ),
    ]
