# Generated by Django 5.1 on 2025-02-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_modeledvideo_subtitle_block_modeledvideo_title_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='diamond',
            name='is_home',
            field=models.BooleanField(default=False, verbose_name='Вывод на главную страницу'),
        ),
    ]
