# Generated by Django 5.1 on 2025-02-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_modeledfoto_is_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='sketchfoto',
            name='is_home',
            field=models.BooleanField(default=False, verbose_name='Публикация на главной'),
        ),
    ]
