# Generated by Django 4.2 on 2025-02-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_weddingrings_is_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='is_home',
            field=models.BooleanField(default=False, verbose_name='Публикация на главной'),
        ),
    ]
